// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF6lJmL2r-mzWr3Uy1A4Uuv9TTLN5X1jE',
    appId: '1:70284662916:web:39685613fe8d61b4364ad1',
    messagingSenderId: '70284662916',
    projectId: 'andaru-elearning',
    authDomain: 'andaru-elearning.firebaseapp.com',
    storageBucket: 'andaru-elearning.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQCT8ra7NuCR4urOgtg4zULG9mkWrwWI',
    appId: '1:70284662916:android:16e422f09bb059d3364ad1',
    messagingSenderId: '70284662916',
    projectId: 'andaru-elearning',
    storageBucket: 'andaru-elearning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKJOTcT0XDcVju_3xHHIbCmzr_wu7-1g',
    appId: '1:70284662916:ios:62a7e46f591daf1e364ad1',
    messagingSenderId: '70284662916',
    projectId: 'andaru-elearning',
    storageBucket: 'andaru-elearning.firebasestorage.app',
    iosBundleId: 'com.example.ubtsimulation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKJOTcT0XDcVju_3xHHIbCmzr_wu7-1g',
    appId: '1:70284662916:ios:62a7e46f591daf1e364ad1',
    messagingSenderId: '70284662916',
    projectId: 'andaru-elearning',
    storageBucket: 'andaru-elearning.firebasestorage.app',
    iosBundleId: 'com.example.ubtsimulation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF6lJmL2r-mzWr3Uy1A4Uuv9TTLN5X1jE',
    appId: '1:70284662916:web:fafc6f15b0c9fae6364ad1',
    messagingSenderId: '70284662916',
    projectId: 'andaru-elearning',
    authDomain: 'andaru-elearning.firebaseapp.com',
    storageBucket: 'andaru-elearning.firebasestorage.app',
  );
}
